### PR TITLE
Results section

### PR DESCRIPTION
**Pull request by tristaaan**
Not ready yet.

### CODE REVIEW

**Comment by tristaaan** [comment]
Requesting early feedback. I’m conflicted about including the tsne confusion matrices every time.

**Comment by ankurshukla03** [comment]
- Report length should be maximum of 5 pages with all the sections but now when i compile without conclusion it's 6 pages already. So maybe we can either remove the confusion matrix or just show the confusion matrix of the model using PCA. Check the report in latex [here].(https://www.sharelatex.com/read/dyvgnjbssbmk)
- [ ] Undefined reference
             ``` (figure \ref{spectrum}). ```

**Review by diegocasmo — COMMENTED** [review]
This is going in the right direction, good discussion about the average accuracy and the variance among them! A few comments:

- [x] Undefined reference
  - ``\ref{spectrum}`` (missing ``fig:``)
- [x] ``less accurate than the competing supervised methods`` for a second I thought you meant RF was also a supervised method, maybe some re-wording would be helpful
- I would advise to mention somewhere that supervised methods are kind of an 'obvious' choice (i.e. we have been given labels, let's use them!)
- [x] Honestly, I don't see any reason to include the t-SNE confusion matrices. I think the PCA ones will suffice. For instance, in the implementation section, I briefly mentioned k-fold and leave-one-out validation, but did not explain anything else about these, since the results weren't great. Because of that, I think we should instead focus only on PCA (anyways, we still have the entire notebook in the repo, which we'll submit too)?

**Review by ankurshukla03 — APPROVED** [review]

**Comment by diegocasmo** [comment]
> Report length should be maximum of 5 pages

I would advise not to worry too much about this for now, we can always make it shorter afterwards :)

**Comment by tristaaan** [comment]
- [x] We can make the figures one row, we really don't refer to the tsne ones at all.

**Pull request merged**
